name: build vue app

on:
    push:
        branches:
            - main
jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node: ['16' ]

        name: Node ${{ matrix.node }} - build vue app

        steps:
            - uses: actions/checkout@v2

            - name: Setup node
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node }}

            - name: Install dependencies
              run: npm install

            - name: Build app
              run: make build

            - name: Restore the [package-lock.json] file
              run: git checkout HEAD package-lock.json

            - name: Commit changes
              uses: stefanzweifel/git-auto-commit-action@v4.0.0
              with:
                  commit_message: build vue app
                  commit_options: '--no-verify'
