name: release

on:
    push:
        branches:
            - main

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2.3.1
              with:
                  fetch-depth: 1

            - name: Install dependencies
              run: npm ci

            - name: Build
              run: |
                make build
                make create-cname

            - name: Deploy 🚀
              uses: JamesIves/github-pages-deploy-action@4.1.7
              with:
                  branch: gh-pages
                  folder: dist
